export default [
    {
        name: '设计语言',
        icon: 'heart',
        items: [
            {
                title: 'Google Design',
                desc: '谷歌官方 UI 设计语言',
                logo: './logos/googledesign.png',
                href: 'https://design.google',
                sort: 1000,
            },
            {
                title: 'Material Design',
                desc: '谷歌推出的全新风格的 UI 设计语言',
                logo: './logos/material.ico',
                href: 'https://material.io',
                sort: 1000,
            },
            {
                title: 'Microsoft Design',
                desc: '微软官方 UI 设计语言',
                logo: './logos/microsoft.png',
                href: 'https://www.microsoft.com/design',
                sort: 1000,
            },
            {
                title: 'Fluent Design',
                desc: '微软推出的全新风格的 UI 设计语言',
                logo: './logos/fluentdesign.png',
                href: 'https://www.microsoft.com/design/fluent/',
                sort: 1000,
            },
            {
                title: 'Apple Design',
                desc: '苹果官方 UI 设计语言',
                logo: './logos/apple.ico',
                href: 'https://www.microsoft.com/design',
                sort: 1000,
            },
            {
                title: 'Ant Design',
                desc: '蚂蚁金服开源的一个 UI 设计语言',
                logo: './logos/antd.png',
                href: 'https://ant.design',
                sort: 1000,
            },
        ]
    },
    {
        name: '前端框架',
        icon: 'heart',
        items: [
            {
                title: 'React',
                desc: '用于构建用户界面的 JavaScript 库',
                logo: './logos/react.ico',
                href: 'https://reactjs.org',
                sort: 1000,
            },
            {
                title: 'Vue',
                desc: '渐进式 JavaScript 框架',
                logo: './logos/vue.png',
                href: 'https://vuejs.org',
                sort: 1000,
            },
            {
                title: 'Angular',
                desc: '一套支持移动端和桌面端多平台的 Web 框架',
                logo: './logos/angular.png',
                href: 'https://angular.io',
                sort: 1000,
            },
            {
                title: 'Bootstrap',
                desc: '世界上最流行的 HTML、CSS 和 JS 库',
                logo: './logos/bootstrap.png',
                href: 'https://getbootstrap.com',
                sort: 1000,
            },
            {
                title: 'TypeScript',
                desc: '一种给 JavaScript 添加特性的语言扩展',
                logo: './logos/typescript.png',
                href: 'https://www.typescriptlang.org',
                sort: 1000,
            },
            {
                title: 'jQuery',
                desc: '一个快速、小巧、功能丰富并且永远不过时的 JavaScript 库',
                logo: './logos/jquery.ico',
                href: 'https://jquery.com',
                sort: 1000,
            },
            {
                title: 'Element',
                desc: '为开发者、设计师和产品经理准备的基于 Vue 2.0 的桌面端组件库',
                logo: './logos/element.ico',
                href: 'https://element.eleme.io',
                sort: 1000,
            },
            {
                title: 'Foundation',
                desc: '世界上最高级的响应式前端框架',
                logo: './logos/foundation.png',
                href: 'https://foundation.zurb.com',
                sort: 1000,
            },
            {
                title: 'Flat UI',
                desc: '基于 Bootstrap 的扁平化用户界面套件',
                logo: './logos/flatui.png',
                href: 'http://designmodo.github.io/Flat-UI/',
                sort: 1000,
            },
            {
                title: 'Electron',
                desc: '使用 JavaScript, HTML 和 CSS 构建跨平台的桌面应用',
                logo: './logos/electron.ico',
                href: 'https://electronjs.org',
                sort: 1000,
            },
            {
                title: 'Flutter',
                desc: '谷歌开源的跨平台 UI 开发框架',
                logo: './logos/flutter.png',
                href: 'https://flutter.dev',
                sort: 1000,
            },
            {
                title: 'Sass',
                desc: '世界上最成熟，最稳定，最强大的专业级CSS扩展语言',
                logo: './logos/sass.png',
                href: 'https://sass-lang.com',
                sort: 1000,
            },
            {
                title: 'Less',
                desc: '一种动态样式语言',
                logo: './logos/less.png',
                href: 'http://lesscss.org',
                sort: 1000,
            },
            // {
            //     title: 'Mint UI',
            //     desc: '基于 Vue.js 的移动端组件库',
            //     logo: './logos/mintui.png',
            //     href: 'http://mint-ui.github.io',
            //     sort: 1000,
            // },
            
        ]
    },
];