export default [
    {
        name: '设计规范',
        icon: 'crown',
        items: [
            {
                title: 'Google Design',
                desc: 'Google 设计官网',
                logo: './logos/googledesign.png',
                href: 'https://design.google',
                sort: 1000,
            },
            {
                title: 'Material Design',
                desc: '材料设计，是由 Google 推出的全新的跨平台设计语言',
                logo: './logos/material.ico',
                href: 'https://material.io',
                sort: 1000,
            },
            {
                title: 'Microsoft Design',
                desc: 'Microsoft 设计官网',
                logo: './logos/microsoft.png',
                href: 'https://www.microsoft.com/design/',
                sort: 1000,
            },
            {
                title: 'Fluent Design',
                desc: '流畅设计，是由 Microsoft 推出的全新的跨平台设计语言',
                logo: './logos/fluentdesign.png',
                href: 'https://www.microsoft.com/design/fluent/',
                sort: 1000,
            },
            {
                title: 'Apple Design',
                desc: 'Apple 设计官网',
                logo: './logos/apple.ico',
                href: 'https://developer.apple.com',
                sort: 1000,
            },
            {
                title: 'Human Interface Guidelines',
                desc: 'Apple 人机界面指南，获取深入的信息和 UI 资源，以设计与 Apple 平台无缝集成的优秀应用程序',
                logo: './logos/apple.ico',
                href: 'https://developer.apple.com/design/human-interface-guidelines/',
                sort: 1000,
            },
            {
                title: 'Ant Design',
                desc: '蚂蚁金服设计服务平台',
                logo: './logos/antdesign.png',
                href: 'https://design.alipay.com',
                sort: 1000,
            }
        ]
    },
    {
        name: '开发框架',
        icon: 'bulb',
        items: [
            {
                title: 'React',
                desc: '用于构建用户界面的 JavaScript 库',
                logo: './logos/react.ico',
                href: 'https://reactjs.org',
                sort: 1000,
            },
            {
                title: 'Vue',
                desc: '渐进式 JavaScript 框架',
                logo: './logos/vue.png',
                href: 'https://vuejs.org',
                sort: 1000,
            },
            {
                title: 'Angular',
                desc: '一套支持移动端和桌面端多平台的 Web 框架',
                logo: './logos/angular.png',
                href: 'https://angular.io',
                sort: 1000,
            },
            {
                title: 'Bootstrap',
                desc: '世界上最流行的 HTML、CSS 和 JS 库',
                logo: './logos/bootstrap.png',
                href: 'https://getbootstrap.com',
                sort: 1000,
            },
            {
                title: 'TypeScript',
                desc: '一种给 JavaScript 添加特性的语言扩展',
                logo: './logos/typescript.png',
                href: 'https://www.typescriptlang.org',
                sort: 1000,
            },
            {
                title: 'jQuery',
                desc: '一个快速、小巧、功能丰富并且永不过时的 JavaScript 库',
                logo: './logos/jquery.ico',
                href: 'https://jquery.com',
                sort: 1000,
            },
            {
                title: 'Ant Design of React',
                desc: '基于 Ant Design 设计体系的 React UI 组件库，主要用于研发企业级中后台产品',
                logo: './logos/antd.png',
                href: 'https://ant.design',
                sort: 1000,
            },
            {
                title: 'Element',
                desc: '为开发者、设计师和产品经理准备的基于 Vue 2.0 的桌面端组件库',
                logo: './logos/element.ico',
                href: 'https://element.eleme.io',
                sort: 1000,
            },
            {
                title: 'Foundation',
                desc: '世界上最高级的响应式前端框架',
                logo: './logos/foundation.png',
                href: 'https://foundation.zurb.com',
                sort: 1000,
            },
            {
                title: 'Flat UI',
                desc: '基于 Bootstrap 的扁平化用户界面套件',
                logo: './logos/flatui.png',
                href: 'http://designmodo.github.io/Flat-UI/',
                sort: 1000,
            },
            {
                title: 'Electron',
                desc: '使用 JavaScript、HTML 和 CSS 构建跨平台的桌面应用',
                logo: './logos/electron.ico',
                href: 'https://electronjs.org',
                sort: 1000,
            },
            {
                title: 'Flutter',
                desc: '谷歌开源的跨平台 UI 开发框架',
                logo: './logos/flutter.png',
                href: 'https://flutter.dev',
                sort: 1000,
            },
            {
                title: 'Sass',
                desc: '世界上最成熟、最稳定、最强大的专业级 CSS 扩展语言',
                logo: './logos/sass.png',
                href: 'https://sass-lang.com',
                sort: 1000,
            },
            {
                title: 'Less',
                desc: '一种开源动态样式语言，受启发于 Sass',
                logo: './logos/less.png',
                href: 'http://lesscss.org',
                sort: 1000,
            },
        ]
    },
    {
        name: '素材下载',
        icon: 'gift',
        items: [
            {
                title: 'Librestock',
                desc: '免费照片和影片素材搜索引擎',
                logo: './logos/librestock.png',
                href: 'https://librestock.com',
                sort: 1000,
            },
            {
                title: 'Unsplash',
                desc: '搜索免费的高分辨率照片',
                logo: './logos/unsplash.png',
                href: 'https://unsplash.com',
                sort: 1000,
            },
            {
                title: 'Gratisography',
                desc: '提供奇特、有创意并且永远免费的照片',
                logo: './logos/gratisography.png',
                href: 'https://gratisography.com',
                sort: 1000,
            },
            {
                title: 'Pixabay',
                desc: '惊人的免费图片，由社区分享的百万张图片和视频',
                logo: './logos/pixabay.png',
                href: 'https://pixabay.com',
                sort: 1000,
            },
            {
                title: 'Pexels',
                desc: '才华横溢的摄影作者在这里免费分享最精彩的素材照片和视频',
                logo: './logos/pexels.png',
                href: 'https://www.pexels.com',
                sort: 1000,
            },
            {
                title: 'Themeforest',
                desc: '国外优质 WordPress 主题、网站模板 交易平台',
                logo: './logos/themeforest.png',
                href: 'https://themeforest.net',
                sort: 1000,
            },
            {
                title: 'Templated',
                desc: '收集免费的 CSS、HTML5 和响应式网站模板',
                logo: './logos/templated.png',
                href: 'https://templated.co',
                sort: 1000,
            },
            {
                title: 'Just Free Slides',
                desc: '高品质免费演示模板、PowerPoint、主题演讲、谷歌幻灯片',
                logo: './logos/justfreeslide.png',
                href: 'https://justfreeslide.com',
                sort: 1000,
            },
        ]
    },
    
];