export default [
    {
        name: '必备神器',
        icon: 'cloud',
        items: [
            {
                title: 'Everything',
                desc: '基于名称快速定位文件和文件夹的搜索工具，其安装轻量、界面简洁、速度之快令人震惊。',
                logo: './logos/everything.png',
                href: 'https://www.voidtools.com',
                sort: 1000,
            },
            {
                title: 'Curl',
                desc: '可以在命令行或脚本中使用的数据传输工具，常用来请求 Web 服务器。其开源免费、功能强大，使用熟练完全可以取代类似 Postman 的图形界面工具。',
                logo: './logos/curl.png',
                href: 'https://curl.haxx.se',
                sort: 1000,
            },
            {
                title: 'Cmder',
                desc: '一款 Windows 环境下具有 Linux 温度的便携式命令提示符工具。',
                logo: './logos/cmder.png',
                href: 'https://cmder.net',
                sort: 1000,
            },
            {
                title: '7-Zip',
                desc: '一款拥有极高压缩比的开源压缩软件。',
                logo: './logos/7zip.png',
                href: 'https://www.7-zip.org',
                sort: 1000,
            },
        ],
    },
    {
        name: '在线工具',
        icon: 'cloud',
        items: [
            {
                title: 'VirSCAN',
                desc: '多引擎在线病毒扫描网，当前支持 47 款杀毒引擎。',
                logo: './logos/virscan.png',
                href: 'http://www.virscan.org',
                sort: 1000,
            },
            {
                title: 'draw.io',
                desc: '免费的在线图表软件，可于制作流程图、流程图、组织结构图、UM、ER 和网络图等。',
                logo: './logos/drawio.png',
                href: 'https://www.draw.io',
                sort: 1000,
            },
            {
                title: 'Aconvert',
                desc: '免费在线转换各种文档、电子书、图像、图标、视频、音频和档案文件。',
                logo: './logos/aconvert.png',
                href: 'https://www.aconvert.com',
                sort: 1000,
            },
            {
                title: 'Nginx Config',
                desc: '一款实用的 Nginx 配置在线生成工具。',
                logo: './logos/nginxconfig.png',
                href: 'https://nginxconfig.io',
                sort: 1000,
            },
            {
                title: 'TinyPNG',
                desc: '最好的 JPEG 图像压缩工具，可将图像压缩 40-60%，使您的网站更快，节省带宽。',
                logo: './logos/tinypng.png',
                href: 'https://tinypng.com',
                sort: 1000,
            },
            {
                title: 'Squoosh',
                desc: '由谷歌实验室发布的一款图像压缩 PWA，使用同类最佳的编解码器压缩图像, 同时可让您深入了解各种图像压缩器提供的高级选项。',
                logo: './logos/squoosh.png',
                href: 'https://squoosh.app',
                sort: 1000,
            },
            {
                title: 'Remove.bg',
                desc: '超级强大的免费 AI 抠图工具，上传图片 5 秒内 100% 自动移除背景。',
                logo: './logos/removebg.png',
                href: 'https://www.remove.bg',
                sort: 1000,
            },
            {
                title: 'Codeimg',
                desc: '一款可以把源代码转换成漂亮图片的在线工具，以便于在社区分享。',
                logo: './logos/codeimg.png',
                href: 'https://codeimg.io',
                sort: 1000,
            },
            {
                title: 'SharpLab',
                desc: '可以让您看到 .NET 平台代码的编译中间过程和结果，并更好地理解 .NET 平台语言。',
                logo: './logos/sharplab.png',
                href: 'https://sharplab.io',
                sort: 1000,
            },
            {
                title: 'Regex101',
                desc: '在线正则表达式测试、调试工具，支持 PHP、PCRE、Python、Golang 和 JavaScript 等编程语言。',
                logo: './logos/regex101.png',
                href: 'https://regex101.com',
                sort: 1000,
            },
            {
                title: 'File Examples',
                desc: '专为开发、设计、测试人员设计的服务，您可以在这下载到具有多种分辨率或大小以及各种格式的样例文件，供测试或演示使用。',
                logo: './logos/fileexamples.png',
                href: 'https://file-examples.com',
                sort: 1000,
            },
            {
                title: 'Mockaroo',
                desc: '可以生成真实的测试数据用于应用程序的测试，同时提供和在线 API Mocking 工具。',
                logo: './logos/mockaroo.png',
                href: 'https://mockaroo.com',
                sort: 1000,
            },
            {
                title: 'Hat.sh',
                desc: '一个免费、快速、安全且无服务器的文件加密工具。',
                logo: './logos/hatsh.png',
                href: 'https://hat.sh',
                sort: 1000,
            },
            {
                title: 'geojson.io',
                desc: '一个快速、简单的地图数据编辑器。',
                logo: './logos/geojson.png',
                href: 'http://geojson.io',
                sort: 1000,
            },
            {
                title: 'Scribens',
                desc: '一款免费好用的英语语法检查工具，它可以检查您的文本段落语法、发现单词拼写错误。',
                logo: './logos/scribens.png',
                href: 'https://www.scribens.com',
                sort: 1000,
            },
        ]
    },
    {
        name: '谷歌插件',
        icon: 'chrome',
        items: [
            {
                title: 'Octotree',
                desc: '让您正在 GitHub 上浏览的项目显示代码树，适合探索项目代码结构，实现快速跳转。',
                logo: './logos/octotree.png',
                href: 'https://www.octotree.io',
                sort: 1000,
            },
            {
                title: 'Sourcegraph',
                desc: '一个开源的功能齐全的代码搜索和导航工具，在 GitHub 上可以像在 IDE 中一样，支持转到定义、查看引用等功能。',
                logo: './logos/sourcegraph.png',
                href: 'https://github.com/sourcegraph/sourcegraph',
                sort: 1000,
            },
            {
                title: 'OneTab',
                desc: '一款标签页聚合工具，可降低内存占用并减少标签混乱现象。',
                logo: './logos/onetab.png',
                href: 'https://www.one-tab.com',
                sort: 1000,
            },
            {
                title: 'Tampermonkey',
                desc: '一款免费的浏览器扩展和最为流行的用户脚本管理器。',
                logo: './logos/tampermonkey.png',
                href: 'https://www.tampermonkey.net',
                sort: 1000,
            },
            {
                title: 'Restlet Client',
                desc: '一款颜值比较高的轻量级 REST API 测试工具，后续更名为 Talend API Tester 继续提供服务。',
                logo: './logos/restletclient.png',
                href: 'https://restlet.com/modules/client/',
                sort: 1000,
            },
            {
                title: 'LastPass',
                desc: '密码管理器、自动填表、随机密码生成器和安全数字钱包应用程序。',
                logo: './logos/lastpass.png',
                href: 'https://lastpass.com',
                sort: 1000,
            },
            {
                title: 'Proxy SwitchyOmega',
                desc: '可以轻松快捷的管理和切换多个代理设置。',
                logo: './logos/switchyomega.png',
                href: 'https://www.one-tab.com',
                sort: 1000,
            },
            {
                title: 'WhatRuns',
                desc: '可帮助您通过单击按钮识别任何网站上使用的技术。',
                logo: './logos/whatruns.png',
                href: 'https://www.whatruns.com',
                sort: 1000,
            },
            {
                title: 'Adblock Plus',
                desc: '世界排名第一的免费广告拦截程序。',
                logo: './logos/adblockplus.png',
                href: 'https://adblockplus.org',
                sort: 1000,
            },
            {
                title: 'IE Tab',
                desc: '在标签页中以 IE 内核显示网页。',
                logo: './logos/ietab.png',
                href: 'https://www.ietab.net',
                sort: 1000,
            },
            {
                title: 'Awesome Screenshot',
                desc: '录屏、捕获整个页面或任何部分，矩形、圆形、箭头、线条和文字，模糊敏感信息，一键上传分享注释，支持 PNG 和链接。',
                logo: './logos/awesomescreenshot.png',
                href: 'https://www.awesomescreenshot.com',
                sort: 1000,
            },

        ]
    },
];